# Generated by Django 2.0.1 on 2018-02-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_auto_20180206_0928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schlüssel1', models.CharField(max_length=20)),
                ('schlüssel2', models.CharField(max_length=20)),
                ('nachricht', models.TextField()),
            ],
        ),
    ]
