# Generated by Django 2.0.1 on 2018-02-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='title',
            field=models.CharField(default='Kein Titel', max_length=50),
        ),
    ]
