# Generated by Django 2.0.1 on 2018-02-07 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_mail_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mail',
            old_name='schlüssel1',
            new_name='mail',
        ),
    ]
