# Generated by Django 2.0.1 on 2018-02-07 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_auto_20180207_0934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mail',
            old_name='schlüssel2',
            new_name='Schlüssel',
        ),
    ]
