# Generated by Django 2.0.1 on 2018-02-07 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0009_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='Schlüssel',
        ),
    ]
